"""add address column

Revision ID: 544fcad95828
Revises: 9048ef3e0628
Create Date: 2026-05-22 04:33:43.755601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '544fcad95828'
down_revision: Union[str, None] = '9048ef3e0628'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seller', sa.Column('address', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seller', 'address')
    # ### end Alembic commands ###
