"""add client contact

Revision ID: fe5e83047c52
Revises: a9252b977ed8
Create Date: 2026-06-04 03:13:46.711250

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe5e83047c52'
down_revision: Union[str, None] = 'a9252b977ed8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipment', sa.Column('client_contact_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('shipment', sa.Column('client_contect_phone', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shipment', 'client_contect_phone')
    op.drop_column('shipment', 'client_contact_email')
    # ### end Alembic commands ###
